control:
  longitudinal_control:
    pid_d: 0.0
    pid_i: 0.1
    pid_p: 1.0
  pure_pursuit:
    crosstrack_gain: 2.0
    desired_speed: 2.0
    lookahead: 2.0
    lookahead_scale: 3.0
  recovery:
    brake_amount: 0.5
    brake_speed: 2.0
model_predictive_controller:
  dt: 0.1
  lookahead: 20
run:
  computation_graph:
    components:
    - state_estimation:
        inputs: []
        outputs:
        - vehicle
    - roadgraph_update:
        inputs:
        - vehicle
        outputs:
        - roadgraph
    - obstacle_detection:
        inputs:
        - vehicle
        outputs:
        - obstacles
    - agent_detection:
        inputs:
        - vehicle
        outputs:
        - agents
    - lane_detection:
        inputs:
        - vehicle
        - roadgraph
        outputs:
        - vehicle_lane
    - sign_detection:
        inputs:
        - vehicle
        - roadgraph
        outputs:
        - roadgraph.signs
    - environment_detection:
        inputs:
        - vehicle
        outputs:
        - environment
    - intent_estimation:
        inputs:
        - vehicle
        - roadgraph
        - agents
        outputs:
        - agent_intents
    - relations_estimation:
        inputs:
        - vehicle
        - roadgraph
        - agents
        - obstacles
        outputs:
        - relations
    - predicate_evaluation:
        inputs:
        - vehicle
        - roadgraph
        - agents
        - obstacles
        outputs:
        - predicates
    - perception_normalization:
        inputs:
        - all
        outputs: []
    - mission_execution:
        inputs: []
        outputs:
        - mission
    - route_planning:
        inputs:
        - vehicle
        - roadgraph
        - mission
        outputs:
        - route
    - driving_logic:
        inputs:
        - all
        outputs:
        - intent
    - motion_planning:
        inputs:
        - all
        outputs:
        - trajectory
    - trajectory_tracking:
        inputs:
        - vehicle
        - trajectory
        outputs: []
  description: Run the yielding trajectory planner on the real vehicle with faked
    perception
  drive:
    perception:
      agent_detection: pedestrian_detection.FakePedestrianDetector2D
      perception_normalization: StandardPerceptionNormalizer
      state_estimation: GNSSStateEstimator
    planning:
      motion_planning: longitudinal_planning.YieldTrajectoryPlanner
      relations_estimation: pedestrian_yield_logic.PedestrianYielder
      route_planning:
        args:
        - GEMstack/knowledge/routes/forward_15m.csv
        - start
        type: StaticRoutePlanner
      trajectory_tracking:
        print: true
        type: pure_pursuit.PurePursuitTrajectoryTracker
  log:
    components:
    - state_estimation
    - agent_detection
    - motion_planning
    ros_topics: null
    vehicle_interface: true
  mission_execution: StandardExecutor
  mode: hardware
  name: launch/pedestrian_detection_fake_real.yaml
  recovery:
    planning:
      trajectory_tracking:
        type: recovery.StopTrajectoryTracker
  replay:
    components: []
    log: null
    ros_topics: []
  vehicle_interface: gem_hardware.GEMHardwareInterface
simulator:
  dt: 0.01
  real_time_multiplier: 1.0
vehicle:
  calibration:
    calibration_date: '2023-08-31'
    front_radar_location:
    - 1.45
    - 0
    - 0.07
    gnss_location:
    - 1.1
    - 0.0
    - 0.3
    gnss_yaw: 0.0
    reference: rear_axle_center
    top_lidar_location:
    - -0.12
    - 0
    - 1.6
  control_defaults:
    accelerator_pedal_speed: 3.0
    brake_pedal_speed: 3.0
    steering_wheel_speed: 2.0
  dynamics:
    acceleration_model: v1_hang
    accelerator_active_range:
    - 0.5
    - 1.0
    aerodynamic_drag_coefficient: 0.01
    brake_active_range:
    - 0.2
    - 1
    gravity: 9.81
    internal_dry_deceleration: 0.2
    internal_viscous_deceleration: 0.05
    lateral_friction: 1.0
    longitudinal_friction: 1.0
    mass: 200.0
    max_accelerator_acceleration:
    - 0.0
    - 5.0
    max_accelerator_acceleration_reverse: 2.5
    max_accelerator_power:
    - 0.0
    - 10000.0
    max_accelerator_power_reverse: 10000.0
    max_brake_deceleration: 5.0
  enable_through_joystick: true
  geometry:
    bounds:
    - - -0.35
      - 2.1
    - - -0.85
      - 0.85
    - - 0
      - 2.08
    height: 2.08
    length: 2.45
    max_steering_angle: 11.0
    max_wheel_angle: 0.6108
    min_steering_angle: -11.0
    min_wheel_angle: -0.6108
    wheel_radius: 0.28
    wheelbase: 1.75
    width: 1.7
  limits:
    max_acceleration: 1.0
    max_accelerator_pedal: 0.75
    max_brake_pedal: 0.75
    max_deceleration: 2.0
    max_reverse_speed: 0.25
    max_speed: 2.5
    max_steering_rate: 2.0
  max_command_rate: 10.0
  max_gear: 1
  name: GEM
  num_wiper_settings: 1
  version: e2
